### ISSUE TITLE
Code block styling in .epub version

### ISSUE THREAD

**Issue by chrisboyce** [skerkour/black-hat-rust#5]
While the `pdf` and `mobi` formats show the code blocks in fixed-width font, it seems that the `epub` version does not (at least in [calibre](https://calibre-ebook.com/) 3.21). 

![image](https://user-images.githubusercontent.com/1100198/107865448-470ae200-6e1b-11eb-8e31-622c78c859b7.png)

**Comment by skerkour** [comment]
Thank you for the feedback!
It's for sure a bug and not a feature and thus need to be fixed.

Do you have any idea about the root cause?

**Comment by chrisboyce** [comment]
After poking at the source for a bit, I realized that the font it was using for code blocks (Courier New) was not a font I had installed locally. After installing it, the code blocks are showing up correctly. I'm not sure how much control you have over the content that's generated, but if the styling can be changed from 
```css
.c0 {
    color: #000000;
    font-weight: 400;
    text-decoration: none;
    vertical-align: baseline;
    font-size: 11pt;
    font-family: "Courier New";
    font-style: normal;
}
```

to 

```css
.c0 {
    color: #000000;
    font-weight: 400;
    text-decoration: none;
    vertical-align: baseline;
    font-size: 11pt;
    font-family: "Courier New", monospace; /* <---- added "monospace" fallback */
    font-style: normal;
}
```

then the ebook viewer should fall back on whichever monospace fonts they have locally if the named font isn't found.
